# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://localhost:8080/login
Content-Type: application/json

{
  "username": "youngxhui",
  "password": "12qw"
}


###

POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "youngxhui",
  "password": "12qw"
}

###

GET http://localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ5b3VuZ3hodWkiLCJleHAiOjE1NzIyNTk4NjcsImp0aSI6Ilx1MDAwNSIsImlhdCI6MTU3MjE3MzQ2NywiaXNzIjoiZ2luIGhlbGxvIiwibmJmIjoxNTcyMTczNDY3LCJzdWIiOiJsb2dpbiJ9.p4VC-Y-Xc6Bhi_Ae6r2KSCayEs6gd0vzPtstWuy43Vs
###